MyProject/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MyProject.views.home', name='home'),
    # url(r'^MyProject/', include('MyProject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^home/$', 'MyProject.List.views.List'),
)

MyProject/List/models.py
from django.db import models
from django.forms import ModelForm

TYPE_CHOICES = (
	('DO', 'Do This!'),
	('GET', 'Get This!'),
	('REM', 'Remember This!'),
)

class Item(models.Model):
	task = models.CharField(max_length=150)
	typs = models.CharField(max_length=3, choices=TYPE_CHOICES)
	due = models.DateField()
	alert = models.BooleanField()
	active = models.BooleanField(default = True)

	def __str__(self):
		return self.task

class ItemForm(ModelForm):

	def __init__(self, *args, **kwargs):
		super(ItemForm, self).__init__(*args, **kwargs)
		self.fields['task'].label = "Don't forget"
		self.fields['typs'].label = "Pick a list"
		self.fields['due'].label = "Do by"
		self.fields['alert'].label = "Remind me"
	
	class Meta:
		model = Item
		exclude = ('active',)

MyProject/List/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from models import ItemForm, Item

def List(request):

	if request.method == 'POST':
		form = ItemForm(request.POST) 
		if form.is_valid():
			newItem = form.save()
			return HttpResponseRedirect('')
		else:
			listitems = Item.objects.filter(active="true").order_by("due")
			return render_to_response('list.html',
			{'form':form, 'listitems': listitems},
			context_instance=RequestContext(request))

	else:
		form = ItemForm()
		listitems = Item.objects.order_by("due")

	return render_to_response('list.html',
		{'form':form, 'listitems': listitems},
		context_instance=RequestContext(request))

templates/base.html
<!doctype html>
<html lang="en">
<head>
	<title>No Lose List</title>
	<style type="text/css">
		body
		{
			margin: 0;
			width: 100%;
			height: 100%;
			background-color: #99CCFF;
		}
		{% block style %}{% endblock %}
	</style>
		{% block scripts %}{% endblock %}
	</script>
</head>
<body>
	{% block body %}{% endblock %}
</body>

templates/list.html
{% extends "base.html" %}

{% block style %}
body
{
	font-family:Verdana, Geneva, sans-serif;
}
h1
{
	text-align: center;
}

#fullist
{
	width: 50%;
	float: left;
	background-color: #FFFF99;
	position: relative;
	top: 10%;
	left: 10%;
	min-height: 600px;
	box-shadow: 4px 4px 2px #808080;
}
#additem
{
	width: 15%;
	float: right;
	background-color: #FFFF99;
	right: 5%;
	position: relative;
	top: 20%;
	box-shadow: 4px 4px 2px #808080;
	padding: 20px;
}

ul
{
	list-style-type: none;
}

.clicked
{
	text-decoration: line-through;
}

.fieldWrapper
{
	padding: 5px;
}

#taskitems
{
	font-family:Verdana, Geneva, sans-serif;
}
#duedate
{
	list-style-position: inside;
	font-size: 14px;
}
#clearbutton
{
	padding: 25px;
}

{% endblock %}

{% block scripts %}
	<link type="text/css" rel="Stylesheet"
		href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css"/>
	<script src="http://code.jquery.com/jquery-1.8.2.js"></script>
	<script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$("#id_due").datepicker();
			$("li").live("click",function(){
				$(this).toggleClass("clicked");
  			});
	 		$("button").click(function ()
			{

				$("li").remove('.clicked');
			});
		});
	</script>

{% endblock %}

{% block body %}
<h1>The No-Lose List</h1>
<div id="fullist">
	<ul>
		{% for item in listitems %}
			<li id="taskitems">
				{{ item.task }}
				<ul id="duedate">
					{{ item.due }}
				</ul>
			</li>
		{% endfor %}
	</ul>
</div>
<div id="additem">
	<form action="." method="POST"> {% csrf_token %}
	{% for field in form %}
	<div class="fieldWrapper">
		{{ field.label_tag }}: <br>
		{{ field }}
		{{ field.errors }}
	</div>
	{% endfor %}
	<input type="submit" Value="New Item">
	</form>
	<div id="clearbutton">
		<button>Clear Accomplished Tasks</button>
	</div>
</div>

{% endblock %}